### ISSUE TITLE
Clean-up dead domains

### ISSUE THREAD

**Issue by marcelstoer** [andreis/disposable#11]
I suggest you run a clean-up task from time to time that removes dead domains from your collection. You won't find domains like http://ww8.10minutemail.de/ or http://1mail.ml/ which still exist but may not be used for disposable mail addresses but you'd find domains like http://30minutemail.com/ for which there's no DNS entry anymore.

**Comment by andreis** [comment]
Thank you for your input @marcelstoer 

I don't think dead domains are a big problem, unless there are new legitimate use cases (which is quite unlikely). However, feel free to add the domains you want skipped [here](https://github.com/andreis/disposable/blob/master/.generate#L19), then run the generator and submit a PR. Cheers

**Comment by marcelstoer** [comment]
> I don't think dead domains are a big problem

True, they're not. However, based on the random samples I tested I'd guess that the majority of the entries on your list are dead domains (>60%). I see no point in artificially bloating the list - particularly if detecting and removing the dead ones is trivial. Just run a loop over all items from time to time and check each one with `socket.gethostbyname()`.
