### ISSUE TITLE
sibmail.com issue

### ISSUE THREAD

**Issue by aLEX12213** [andreis/disposable#13]
Hello. Why sibmail.com in your domain files? Sibmail.com is Tomsk located mail system. It works only with            Russian residents of Tomsk. Sibmail.com does not provide "fast mail system" so please remove it from your list. Thanks.

**Comment by aLEX12213** [comment]
http://www.sibmail.com/reg/foreign please view this page.

**Comment by aLEX12213** [comment]
Also I think you can add:  fastmailforyou.net stexsy.com wimsg.com vmani.com msgos.com lackmail.ru emltmp.com

**Comment by andreis** [comment]
Thank you for your input. The list of domains is based on other existing lists (see the code) and on input from the community. I'm unfortunately working around the clock now, but if you want feel free to submit a PR. You need to edit [this](https://github.com/andreis/disposable/blob/master/.generate) file and run it. 👍

**Comment by smeinecke** [comment]
done in PR #15.

**Comment by smeinecke** [comment]
@aLEX12213: The other mentioned domains are either not listed or does not have any active MX record.
