### ISSUE TITLE
A way to add extra domains

### ISSUE THREAD

**Issue by MantasR** [andreis/disposable#19]
Could you provide a way to add some extra domains?

As there are a few new ones which aren't on the list:
@zain.site
@maileme101.com
@stromox.com
@9me.site
@zainmax.net
@dr69.site

Thanks

**Comment by smeinecke** [comment]
Thanks for your help!
Can you provide some kind of page where this domains are public available for disposable mails?

**Comment by smeinecke** [comment]
https://www.temp-mail.org/option/change
Will add parser for that domain to get new domains automatically.

**Comment by HenkerX64** [comment]
API call in JSON format:
http://api.temp-mail.ru/request/domains/format/json/

**Comment by smeinecke** [comment]
@HenkerX64: thanks, but already implemented their API :-) 
They do not return all domains right now + on API documentation page: "Note: New API version is coming soon."
