### ISSUE TITLE
Mailinator domains

### ISSUE THREAD

**Issue by andreis** [andreis/disposable#20]
Received via email:

If you are interested in an additional list see what I recently published: [](https://github.com/GeroldSetz/Mailinator-Domains)

Will be updated on a daily basis with data from my main project ([www.bdea.cc](url)) - which might be also of interest for your

cc thanks @geroldsetz

**Comment by smeinecke** [comment]
@geroldsetz: Just asking, on block-disposable-email.com are 14.147 domains listed, but your github dump only lists about 2.000 hashes - do you plan to dump all domains on github too?

**Comment by GeroldSetz** [comment]
@andreis thanks for the integration!

@smeinecke : the github dump includes mailinator's alternative domains names only - so it is a subset of our whole asset of >14k dea domains. I do not plan to publish everything for free at github. However, www.block-disposable-email.com offers a free plan for up to 200 cals per month that covers the full up-to-date blacklist.

**Comment by smeinecke** [comment]
@GeroldSetz ah, ok! I will try your API 👍
