### ISSUE TITLE
How to continuously add domains from block-disposable-email.com?

### ISSUE THREAD

**Issue by GeroldSetz** [andreis/disposable#24]
Hi Andrei,

thanks for adding my mailiantor-data to your repository. I wonder how you can manage to keep track of all updates that appear on my end (I am not so familiar with github). For example I added another domain recently, see https://github.com/GeroldSetz/Mailinator-Domains/blob/master/mailinator_domains_from_bdea.cc.txt

Gerold

**Comment by andreis** [comment]
Hi Gerold! At this point the process is to run the generator script by hand, update the git repo if there  are any changes, then publish on npm.

This isn't an ideal process so I'm thinking of alternatives. E.g. adding a [postinstall](https://docs.npmjs.com/misc/scripts) script to run the generator, or the option to do it in code (`disposable.update()`?).

Any thoughts on that?

**Comment by smeinecke** [comment]
Hi Gerold! I understand your objection and an automatic build process would be good, BUT:

I think the right way would be to not deliver any result/text files of the script to github. Then everyone that would like to use the script has to install it on their server/system and run the script as cron.

As soon as we publish the list on github, everyone assumes that we maintain the entries in the list itself - which is not true. We already had some issue/pull requests caused by that misunderstanding. We only wrote the tool to merge all lists and don't maintain the lists itself ;)

A "mild" solution would be to create a dedicated repository or branch for the results which is updated by an service.

**Comment by andreis** [comment]
I like your idea @smeinecke. I could set up a cheap VPS for that, or we could even use Travis. With a CI we can even fail a build if too many domains changed, or too many sources are unavailable.

**Comment by smeinecke** [comment]
@andreis hmm.. right, there is cronjob support in Travis (https://docs.travis-ci.com/user/cron-jobs/) - sounds like a nice solution 👍

**Comment by GeroldSetz** [comment]
Hi all,

you all have great ideas! 

Regarding my contribution to this list of disposable email addresses: I wonder if or what type of additional export from www.block-disposable-email.com would help you and the "fetchers" of this list most while keeping my assets. I could for example export a hashed list of:

1) yopmail alternative domains (hundreds) or 
2) every 10th dea domain of our database (regardless of the dea service they are served of) or
3) daily update of emailondeck.com or mytemp.email (almost daily additions of domains)

Your thoughts?

**Comment by GeroldSetz** [comment]
Hi again,

just want to say briefly that I added 52 Mailinator domains to day to https://github.com/GeroldSetz/Mailinator-Domains/blob/master/mailinator_domains_from_bdea.cc.txt

**Comment by GeroldSetz** [comment]
Another 15 domains added.

**Comment by andreis** [comment]
```
Fetched 3271 domains and 4658 hashes
 - 0 domain(s) added
 - 0 domain(s) removed
 - 1 hash(es) added
 - 0 hash(es) removed
```

Data stuff moved [here](https://github.com/andreis/disposable-email-domains), will rewrite the main codebase to use this new model *soon*.

**Comment by GeroldSetz** [comment]
How about this: https://github.com/GeroldSetz/emailondeck.com-domains

Gerold

PS: would be nice to get a link from your Readme to the datasource.

**Comment by smeinecke** [comment]
Added your github repo to credits + activated cron for separate repository with daily updates.
