### ISSUE TITLE
Please add fastmailforyou.net

### ISSUE THREAD

**Issue by VolodymyrTech** [andreis/disposable#27]

**Comment by andreis** [comment]
Thanks for your report. Where did you find this domain? I tried looking into it but I can't find any definitive proof it's being used exclusively for disposable email.

**Comment by andreis** [comment]
Added https://github.com/andreis/disposable-email-domains/commit/25537a20da2212a469352355243666a442c9b216

Will go live when we refactor the code soon™

**Comment by VolodymyrTech** [comment]
Andreis, I found this domain on one of the threads discussing your project. And the domain name kind of suggests. However, the website leads to default apache response. Maybe it is premature to add it. However please check e.g. https://stopforumspam.com/ipcheck/62.210.136.9,
http://botscout.com/ipcheck.htm?ip=46.161.9.36
