### ISSUE TITLE
non-disposable free mail providers

### ISSUE THREAD

**Issue by bago** [andreis/disposable#32]
The following domains are "major" (in their countries) free domains and never been disposable, AFAIK:

> 126.com, 188.com, yeah.net, naver.com, freemail.hu, sina.com, sohu.com, poczta.onet.pl, tom.com, 21cn.com, writeme.com, dr.com, mindless.com

You can open their websites/portal by adding www. in front of them.. but the last 3 that are alternative  domains for the mail.com site.

PS: related to #30, that I opened before checking the list in more detail.

**Comment by smeinecke** [comment]
Thank you for your advice - I will check them later and add them to the whitelist if everything turns out right.

**Comment by smeinecke** [comment]
Added all domains to whitelist (8bb288baaa9dd2d6f17c5d18590c88bd90d3d594).
