### ISSUE TITLE
New domains

### ISSUE THREAD

**Issue by hotgeart** [andreis/disposable#35]
Had spammers on my website with these domains :

- dim-coin.com
- polyswarms.com 
- xgmailoo.com
- mail4gmail.com
- bit2tube.com

They're all on : https://www.stopforumspam.com

- https://www.stopforumspam.com/domain/dim-coin.com
- https://www.stopforumspam.com/domain/polyswarms.com 
- https://www.stopforumspam.com/domain/xgmailoo.com
- https://www.stopforumspam.com/domain/dmail4gmail.com
- https://www.stopforumspam.com/domain/bit2tube.com

**Comment by smeinecke** [comment]
All by https://temp-mail.org/option/change/ - have to check if the crawler does not work anymore.

**Comment by smeinecke** [comment]
Script is still fine but update cron for https://github.com/andreis/disposable-email-domains/ did not work anymore. Fixed + updated now :)
