### ISSUE TITLE
Please remove brainonfire.net

### ISSUE THREAD

**Issue by timmc** [andreis/disposable#41]
`brainonfire.net` is just my personal domain name, and has never hosted disposable email. (About 10 years ago, I had `open.brainonfire.net` aliased to mailinator, but that subdomain hasn't existed for *years* now, and it was always just the subdomain.)

I've also filed a PR against the source list that you probably got it from (https://github.com/wesbos/burner-email-providers/pull/210), but I would appreciate having it added to the whitelist.txt as well, if you don't mind. Apparently it is getting copied around to various lists. -.-

(I would have filed a PR, but I wasn't sure exactly how you manage the source and generated files, or the relationship of the `disposable` vs. `disposable-email-domains` repos.)

**Comment by smeinecke** [comment]
Thanks for the info 👍
I've checked your domain and can confirm it's false positive. Added to whitelist and should be removed from the public files in next update.
