### ISSUE TITLE
Additionnal domains

### ISSUE THREAD

**Issue by akuma8** [andreis/disposable#47]
I have this domains list (see joined file):
[blacklistdomains.txt](https://github.com/andreis/disposable/files/4517316/blacklistdomains.txt)
. 
I compared it with yours and there are some domains that aren't in your list. 
Could you check and add them if necessary.

Thanks

**Comment by smeinecke** [comment]
Thanks for your commission. Could you provide a source for the domains so we can automate the import process for the future?

**Comment by akuma8** [comment]
One of my clients use this list, I absolutely don’t know where he got it but I found useful to share it since I prefer use your list which is more complete. I hope you’ll keep maintaining it
