### ISSUE TITLE
New domains

### ISSUE THREAD

**Issue by Fossil01** [andreis/disposable#49]
Since the other repo continues to get updates but my issue remains ignored I am opening one here:

https://generator.email/ and https://email-fake.com/ generate random emails, they don't list their domains so I build a script and scraped them for 3 days straight.

There are probably more domains, but after 3 days this is the (deduped) list I got: https://kopy.io/20LAz it's almost 15.000 domains.

**Comment by smeinecke** [comment]
Ah, cool. Could you provide your script so I can add that method to our auto update method?

**Comment by Fossil01** [comment]
That is not feasible. It does HTTP requests in a loop to scrape the addresses, it took me 72 hours just to get this list and I dont think thats 100% of what they use.

**Comment by smeinecke** [comment]
Ah, the same method that is already implemented right now...

**Comment by Fossil01** [comment]
Is it? Because I added tons of domains not found in your lists yet.

**Comment by smeinecke** [comment]
We had a "extended" list where the script did not discard "old" entries. I probably have to reactivate that stuff for that 2 hosts again.

**Comment by Fossil01** [comment]
Hmm. Anyway, why not add these to the main list? It's a huge number of currently active domains.

**Comment by smeinecke** [comment]
We do not host "static" lists directly in the script. I will copy your list to gist and add it as "external" list.

**Comment by smeinecke** [comment]
I will update our script to do some "DNS scraping" to fetch all domains monthly.
